#!/bin/bash
if [[ "$NOTIFICATIONTYPE" == "RECOVERY" ]]; then
    SUBJECT="Recovery: $NAGIOS_HOSTNAME"
    MESSAGE="$NAGIOS_HOSTOUTPUT"
elif [[ "$NOTIFICATIONTYPE" == "PROBLEM" ]]; then
    SUBJECT="Alert: $NAGIOS_HOSTNAME"
    MESSAGE="$NAGIOS_HOSTOUTPUT"
elif [[ "$NOTIFICATIONTYPE" == "ACKNOWLEDGEMENT" ]]; then
    SUBJECT="Ack: $NAGIOS_HOSTNAME"
    MESSAGE="$NOTIFICATIONCOMMENT"
fi

/usr/bin/printf "%b" "$MESSAGE\n" | /bin/mail -s "$SUBJECT" $NAGIOS_CONTACTEMAIL
